apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-daemon
  labels:
    app: moon
spec:
  selector:
    matchLabels:
      app: moon
  template:
    metadata:
      labels:
        app: moon
    spec:
      containers:
      - name: multi
        image: wbitt/network-multitool
        volumeMounts:
        - name: syslog
          mountPath: /cluster-log
          subPath: syslog
          readOnly: true
      volumes:
      - name: syslog
        hostPath:
          path: /var/log
