apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2cc
  labels:
    app: repa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: repa
  template:
    metadata:
      labels:
        app: repa
    spec:
      containers:
      - name: multi
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
