apiVersion: v1
kind: Service
metadata:
  name: myserv
spec:
  selector:
    app: repa
  ports:
  - name: tcp-80
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: tcp-8080
    protocol: TCP
    port: 9002
    targetPort: 8080
