apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: echo
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    name: netology-web
    ports:
    - containerPort: 8080
