apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2x
  labels:
    app: rep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rep
  template:
    metadata:
      labels:
        app: rep
    spec:
      containers:
      - name: multi
        image: wbitt/network-multitool
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        command: ["sleep", "infinity"]
