apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2a
  labels:
    app: repa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repa
  template:
    metadata:
      labels:
        app: repa
    spec:
      containers:
      - name: multi
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "3333"
        ports:
        - containerPort: 3333
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
